// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8UGZKk_bc8VRQH53MLFf0U4TKafQ5lJQ',
    appId: '1:866542925821:web:32df81c1dbfb7fc6a1cb94',
    messagingSenderId: '866542925821',
    projectId: 'truth-or-dare-42799',
    authDomain: 'truth-or-dare-42799.firebaseapp.com',
    storageBucket: 'truth-or-dare-42799.appspot.com',
    measurementId: 'G-9JPY0CJPG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH47Cf8Flv_NG250CJ_GuqnT8I6QWrRA8',
    appId: '1:866542925821:android:c8ff2d26b351f61da1cb94',
    messagingSenderId: '866542925821',
    projectId: 'truth-or-dare-42799',
    storageBucket: 'truth-or-dare-42799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL6gN-BonE-_DsHwm8GLWOQXZIZ-TIGVA',
    appId: '1:866542925821:ios:3396527338381d16a1cb94',
    messagingSenderId: '866542925821',
    projectId: 'truth-or-dare-42799',
    storageBucket: 'truth-or-dare-42799.appspot.com',
    iosClientId: '866542925821-6cs4o4jonc1t6i2vanu62g9ql9i5nsjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tOrd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL6gN-BonE-_DsHwm8GLWOQXZIZ-TIGVA',
    appId: '1:866542925821:ios:3396527338381d16a1cb94',
    messagingSenderId: '866542925821',
    projectId: 'truth-or-dare-42799',
    storageBucket: 'truth-or-dare-42799.appspot.com',
    iosClientId: '866542925821-6cs4o4jonc1t6i2vanu62g9ql9i5nsjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tOrd',
  );
}
